name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - run: test -z "$(go fmt ./...)"
        name: Check gofmt

      - run: go vet ./...
        name: go vet

      - run: go build ./...
        name: go build

      - run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          sudo -u postgres createdb admiral_core
          sudo -u postgres createdb admiral_queue
        name: Start PostgreSQL

      - run: DATABASE_URL="postgres://postgres:postgres@localhost:5432/admiral_core?sslmode=disable" go test ./... -count=1 -p 1 -timeout 300s
        name: go test
